DineOut/Controllers/QrController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DineOut.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QRCoder;

namespace DineOut.Controllers
{
    public class QrController : Controller
    {
        DineOutContext DineOutContext = new DineOutContext();
        public IActionResult QrGenerator()
        {
            using (MemoryStream ms = new MemoryStream())
            {

                var profile_id = HttpContext.Session.GetString("restaurant_owner_Id");
                int restaurant_id = DineOutContext.Restaurant.ToList().Find(r => r.RestaurantProfileId == Int32.Parse(profile_id)).RestaurantId;

                string url = "https://dineout20201118022357.azurewebsites.net/CustomerOrder/OrderDetails?menuid=" + getMenuId(restaurant_id) + "&restaurantId=" + restaurant_id;
                QRCodeGenerator oQRCodeGenerator = new QRCodeGenerator();
                QRCodeData oQRCodeData = oQRCodeGenerator.CreateQrCode(url, QRCodeGenerator.ECCLevel.Q);
                QRCode oQRCode = new QRCode(oQRCodeData);

                using (Bitmap oBitmap = oQRCode.GetGraphic(20))
                {
                    oBitmap.Save(ms, ImageFormat.Png);
                    ViewBag.QRCode = "data:image/png;base64," + Convert.ToBase64String(ms.ToArray());

                }

            }
            return View();
        }


        public string getMenuId(int resturant_id)
        {

            DbSet<Restaurant> Restaurant = DineOutContext.Restaurant;
            DbSet<Menu> Menu = DineOutContext.Menu;
            var menud_id = DineOutContext.Menu.Where(r => r.RestaurantId == resturant_id).FirstOrDefault().MenuId;
            return menud_id.ToString();
        }
    }
}

DineOut/Views/Shared/ItemSummary.cshtml
@model Item

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.ItemName
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>

    <form id="@Model.ItemId" asp-action="AddToCart"
          asp-controller="CustomerOrder" method="post">

        <input type="hidden" asp-for="ItemId" />
        <input type="hidden" name="returnUrl"
           value="@*@ViewContext.HttpContext.Request.PathAndQuery()*@" />

        <span class="card-text p-1">
            @Model.Description

            <button type="submit"
                    class="btn btn-success btn-sm pull-right"
                    style="float:right">
                Add to Cart
            </button>
        </span>

    </form>
</div> 

DineOut/Views/Shared/_CustomerLayout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewBag.Title</title>
	<link rel="stylesheet" asp-href-include="/lib/bootstrap/**/*.min.css"
		  asp-href-exclude="**/*-reboot, **/*-grid" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
</head>
<body background="/images/bg.png">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        @if (Context.Session.GetString("customer_id") == null)
        {
            <a asp-controller="Home" asp-action="Index">
                <img class="banner" style="width: 80px" src="/images/logo_transparent.png">
            </a>
        }
        else
        {
            <a asp-controller="Customer" asp-action="Index">
                <img class="banner" style="width: 80px" src="/images/logo_transparent.png">
            </a>
        }


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a asp-controller="Customer" asp-action="Index" class="nav-link">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">

                    <a asp-controller="Home" asp-action="About" class="nav-link">About</a>
                </li>
                @*<li class="nav-item">
                    <a asp-controller="Payment" class="nav-link">Payment</a>
                </li>*@
            </ul>
            <ul class="nav navbar-nav navbar-right">

                @if (Context.Session.GetString("customer_id") == null)
                {
                    <li><a asp-action="CustomerLogin" asp-controller="Customer" class="btn btn-sm btn-success">Customer Login <i class="fas fa-user"></i></a></li>
                
                    <li><a asp-action="OwnerLogin" asp-controller="Restaurant" class="ml-2 btn btn-sm btn-success">Owner Login<i class="fas fa-user"></i></a></li>
                }
                else
                {

                    <li><a asp-action="CustomerLogout" asp-controller="Customer" class="btn btn-sm btn-success">Log Out  <i class="fas fa-user"></i></a></li>
                }
            </ul>
        </div>
    </nav>


    <div class="container" style="margin-top:100px">

        @if (TempData["message"] != null)
        {
            <div class="alert alert-success mt-1">@TempData["message"]</div>
        }

        @RenderBody()
        <hr />
    </div>
	<footer class="text-center bg-light" style="position:page; width:100% !important">
		<div>&copy; Fall 2020 - COMP231 Group4 - Project DineOut</div>
		<div>
			Background image is lisenced by
			<a href='https://pngtree.com/free-backgrounds' target="_blank" >pngtree.com</a>
		</div>
	</footer>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

      
</body>
</html>

DineOut/Views/Shared/_IdentityLayout.cshtml
@{
    Layout = "_Layout";
}

<div class="jumbotron d-flex justify-content-center" style="background-color: rgba(255, 226, 112, 0.8);">
    <div class="card col-md-6 col-sm-offset-4" style= "position: center;">
        <div class="card-body">
            <h3 class="card-title">@ViewBag.Title</h3>
            @RenderBody()
        </div>
    </div>
</div>

DineOut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link rel="stylesheet" asp-href-include="/lib/bootstrap/**/*.min.css"
		  asp-href-exclude="**/*-reboot, **/*-grid" />
	@*<link rel="stylesheet" href="/css/style.css" />*@
	@*<link rel="shortcut icon" href="/images/favicon.png" />*@
</head>
<body background="/images/bg.png">


	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
		<a asp-controller="Home" asp-action="Index">
			<img class="banner" style="width: 80px" src="/images/logo_transparent.png">
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
				</li>
				<li class="nav-item">

					<a asp-controller="Home" asp-action="About" class="nav-link">About</a>
				</li>
			</ul>

            <ul class="nav navbar-nav navbar-right">


                <li><a asp-action="CustomerLogin" asp-controller="Customer" class="btn btn-sm btn-success">Customer Login <i class="fas fa-user"></i></a></li>
               
                <li><a asp-action="OwnerLogin" asp-controller="Restaurant" class="ml-2 btn btn-sm btn-success">Owner Login<i class="fas fa-user"></i></a></li>

            </ul>
		</div>
	</nav>




    <div class="container" style="margin-top:100px">

        @if (TempData["message"] != null)
        {
            <div class="alert alert-success mt-1">@TempData["message"]</div>
        }

        @RenderBody()
        <hr />
    </div>


	<footer class=" text-center bg-light" style="position:page; width:100% !important">
		<p>&copy; Fall 2020 - COMP231 Group4 - Project DineOut</p>
		<p>
			Background image is lisenced by
			<a href='https://pngtree.com/free-backgrounds' target="_blank">pngtree.com</a>
		</p>
	</footer>

	


	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

   
</body>
</html>

DineOut/Views/Shared/_RestaurantLayout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link rel="stylesheet" asp-href-include="/lib/bootstrap/**/*.min.css"
		  asp-href-exclude="**/*-reboot, **/*-grid" />
	<link rel="shortcut icon" href="/images/favicon.png" />
	<link rel="stylesheet" href="/css/style.css" />

</head>
<body background="/images/bg.png">


	<!--Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        @if (Context.Session.GetString("restaurant_owner_Id") == null)
        {
            <a asp-controller="Home" asp-action="Index">
                <img class="banner" style="width: 80px" src="/images/logo_transparent.png">
            </a>
        }
        else
        {
            <a asp-controller="Restaurant" asp-action="Menu">
                <img class="banner" style="width: 80px" src="/images/logo_transparent.png">
            </a>
        }
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
                aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a asp-controller="Restaurant" asp-action="Menu" class="nav-link">
                        Menu
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Orders
                    </a>
                    <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                        <a class="dropdown-item" asp-action="Orders" asp-controller="Restaurant">All Orders</a>
                        <a class="dropdown-item" asp-action="CurrentOrders" asp-controller="Restaurant">Current Orders</a>
                        <a class="dropdown-item" asp-action="CompletedOrders" asp-controller="Restaurant">Completed Orders</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a asp-controller="Qr" asp-action="QrGenerator" class="nav-link">Generate QR Code</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Restaurant" asp-action="Profile" class="nav-link">Profile</a>
                </li>
                <li>
                    <a asp-controller="Restaurant" asp-action="Notification" class="nav-link btn btn-sm btn-outline-danger">Notification</a>
                </li>

            </ul>
            <ul class="nav navbar-nav navbar-right">

                @if (Context.Session.GetString("restaurant_owner_Id") == null)
                {
                <li><a asp-action="CustomerLogin" asp-controller="Customer" class="btn btn-sm btn-success">Customer Login <i class="fas fa-user"></i></a></li>

                <li><a asp-action="OwnerLogin" asp-controller="Restaurant" class="ml-2 btn btn-sm btn-success">Owner Login<i class="fas fa-user"></i></a></li>
                }
                else
                {

                <li><a asp-action="RestaurantLogout" asp-controller="Restaurant" class="btn btn-sm btn-success">Log Out  <i class="fas fa-user"></i></a></li>
                }

            </ul>
        </div>
    </nav>

	@if (TempData["message"] != null)
	{
		<div class="alert alert-success mt-1">@TempData["message"]</div>
	}
	<div class="container" style="margin-top:100px">
		

		@RenderBody()
	</div>
	<hr />
	<footer class="text-center bg-light" style="position:page; width:100% !important">
		<p>&copy; Fall 2020 - COMP231 Group4 - Project DineOut</p>
		<p>
			Background image is lisenced by
			<a href='https://pngtree.com/free-backgrounds' target="_blank">pngtree.com</a>
		</p>
	</footer>


	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    
</body>
</html>