DineOut/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DineOut.Models
{
    public class Menu
    {
        [Key]
        [Column("menu_id")]
        public int MenuId { get; set; }
        [Column("title")]
        public string Title { get; set; }
        [Column("restaurant_id")]
        public int RestaurantId { get; set; }
        [Column("created_on")]
        public DateTime CreatedOn { get; set; }
        public override string ToString()
        {
            return Title;
        }
    }
}

DineOut/Models/Notification.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DineOut.Models
{
    public class Notification
    {
        [Key]
        [Column("notify_id")]
        public int NotifyId { get; set; }
        [Column("send_time")]
        public DateTime SendTime { get; set; }
        [Column("subject")]
        public string Subject { get; set; }
        [Column("content")]
        public string Content { get; set; }
        [Column("failed_info")]
        public string FailedInfo { get; set; }
    }
}

DineOut/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DineOut.Models
{
    public class Order
    {
        [Key]
        [Column("order_id")]
        public int OrderId { get; set; }
        [Column("restaurant_id")]
        public int RestaurantId { get; set; }
        [Column("customer_id")]
        public int CustomerId { get; set; }
        [Column("note")]
        public string Note { get; set; }
        [Column("table_num")]
        public string TableNum { get; set; }
        [Column("status_id")]
        public int StatusId { get; set; }
        [Column("order_date")]
        public DateTime CreatedOn { get; set; }
        public override string ToString()
        {
            return OrderId.ToString();
        }
    }
}

DineOut/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DineOut.Models
{
    public class Restaurant
    {
        [Key]
        [Column("restaurant_id")]
        public int RestaurantId { get; set; }
        [Column("restaurant_name")]
        public string RestaurantName { get; set; }
        [Column("QR_Code")]
        public string QRCode { get; set; }
        [Column("created_on")]
        public DateTime CreatedOn { get; set; }
        public override string ToString()
        {
            return RestaurantName;
        }
        [Column("restaurant_profile_id")]
        public int RestaurantProfileId { get; set; }

        public Menu Menu { get; set; }
    }
}

DineOut/ViewModels/ProfileViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DineOut.Models;

namespace DineOut.ViewModels
{
    public class ProfileViewModel
    {
        public RestaurantProfile restaurantProfile { get; set; }

        public Restaurant restaurant { get; set; }
    }
}

DineOut/Controllers/RestaurantController.cs
using DineOut.Models;
using DineOut.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Security.Claims;
using DineOut.Common;
using Microsoft.AspNetCore.Hosting;
using System.Text;
using System.Security.Cryptography;

namespace DineOut.Controllers
{
    public class RestaurantController : Controller
    {
        AzureConnection AzureConnection = new AzureConnection();
        DineOutContext DineOutContext = new DineOutContext();
        OrderDetailsInfo orderDetailsInfo = new OrderDetailsInfo();  // this a new view model
        List<Order> orders = new List<Order>();

        public RestaurantController()
        {
            
        }

        public IActionResult OwnerLogin() => View();

        public IActionResult OwnerRegistration() => View();


        public IActionResult Orders()
        {
            var profile_id = HttpContext.Session.GetString("restaurant_owner_Id");
            int restautantId = DineOutContext.Restaurant.ToList()
                    .Find(o => o.RestaurantProfileId == Int32.Parse(profile_id))
                    .RestaurantId;
            return View(DineOutContext.Order
                .Where(o => o.RestaurantId == restautantId)
                .OrderBy(o => o.OrderId)
                .ToList());
        }
        public IActionResult CompletedOrders()
        {
            int statusOrder = 5; //A status Order of 5 is considered completed
            var profile_id = HttpContext.Session.GetString("restaurant_owner_Id");
            if (profile_id != null)
            {
                int restautantId = DineOutContext.Restaurant.ToList()
                    .Find(o => o.RestaurantProfileId == Int32.Parse(profile_id))
                    .RestaurantId;
                orders = DineOutContext.Order
                            .Where(o => o.RestaurantId == restautantId)
                            .OrderBy(o => o.OrderId)
                            .ToList()
                            .FindAll(o => o.StatusId == statusOrder);
            }

            return View(orders);
        }
        public IActionResult CurrentOrders()
        {
            var profile_id = HttpContext.Session.GetString("restaurant_owner_Id");
            if (profile_id != null)
            {
                int restautantId = DineOutContext.Restaurant.ToList()
                    .Find(o => o.RestaurantProfileId == Int32.Parse(profile_id))
                    .RestaurantId;
                orders = DineOutContext.Order
                            .Where(o => o.RestaurantId == restautantId)
                            .OrderBy(o => o.OrderId)
                            .ToList()
                            .FindAll(o => o.StatusId != 5);
            }

            //This will populate Orders that are of any statuses but 5
            //Which means Orders that are still open and/or current
            
            return View(orders);
        }

        public IActionResult Profile()
        {
            ProfileViewModel profileInfo = new ProfileViewModel();
            int profile_id = Int32.Parse(HttpContext.Session.GetString("restaurant_owner_Id"));
            int restaurant_id = DineOutContext.Restaurant.ToList().Find(r => r.RestaurantProfileId == profile_id).RestaurantId;
            var menud_id = DineOutContext.Menu.Where(r => r.RestaurantId == restaurant_id).FirstOrDefault().MenuId;


            int restaurantId = restaurant_id;
            int restaurantProfileId = profile_id;
            profileInfo.restaurant = DineOutContext.Restaurant.Find(restaurantId);
            profileInfo.restaurantProfile = DineOutContext.RestaurantProfile.Find(restaurantProfileId);

           
            return View(profileInfo);
        }

        [HttpPost]
        public IActionResult SaveChanges(RestaurantProfile restaurantProfile)
        {
            if (ModelState.IsValid)
            {
                RestaurantProfile profileEntry = DineOutContext.RestaurantProfile
                    .FirstOrDefault(r => r.RestaurantProfileId == restaurantProfile.RestaurantProfileId);
                if (profileEntry != null)
                {
                    profileEntry.Email = restaurantProfile.Email;
                }
                DineOutContext.SaveChanges();
                TempData["message"] = $"Your profile has been updated!";

            }
            return RedirectToAction("Menu");
        }


        public IActionResult SearchString(string searchedString)
        {
            Console.WriteLine(searchedString);
            try
            {
                var orderByID = DineOutContext.Order.Where(r => r.OrderId == Convert.ToInt32(searchedString)).ToList();
                return View("Orders", orderByID);
            }
            catch
            {
                return View("Menu");
            }
        }

        // MENU View
        public IActionResult Menu()
        {
            var profile_id =  HttpContext.Session.GetString("restaurant_owner_Id");
            if (profile_id != null)
            {
                int restaurant_id = DineOutContext.Restaurant.ToList().Find(r => r.RestaurantProfileId == Int32.Parse(profile_id)).RestaurantId;
                var menud_id = DineOutContext.Menu.Where(r => r.RestaurantId == restaurant_id).FirstOrDefault().MenuId;
                var items = DineOutContext.Item.Where(r => r.MenuId == menud_id).ToList();
                return View("Menu", items);
            }
            return RedirectToAction("OwnerLogin");
            

        }

        // MENU CRUD
        public IActionResult Add_Menu(int restaurant_id, string menu_title)
        {
            var profile_id = HttpContext.Session.GetString("restaurant_owner_Id");
            if (profile_id != null)
            {
                var menu_row = DineOutContext.Menu.Where(r => r.RestaurantId == restaurant_id).FirstOrDefault();

                if (menu_row != null)
                {
                    TempData["message"] = $"You already have a menu created!";
                    return RedirectToAction("Index");
                }
                else
                {
                    Menu menu_object = new Menu();
                    menu_object.RestaurantId = restaurant_id;
                    var datetime = DateTime.Now.ToString("yyyy-MM-dd");
                    menu_object.CreatedOn = DateTime.Today;
                    menu_object.Title = menu_title;
                    Console.WriteLine(menu_object);

                    DineOutContext.Add(menu_object);
                    DineOutContext.SaveChanges();

                    TempData["message"] = $"Welcome! Your menu has been created!";
                    return RedirectToAction("Menu");
                }
            }
            return RedirectToAction("OwnerLogin");
        }

        public IActionResult Update_Menu(int restaurant_id, int menu_id, string menu_title)
        {
            var profile_id = HttpContext.Session.GetString("restaurant_owner_Id");
            if (profile_id != null)
            {
                var menu_row = DineOutContext.Menu.Where(r => r.RestaurantId == restaurant_id)
                .Where(r => r.MenuId == menu_id)
                .FirstOrDefault();

                Menu menu_object = menu_row;

                menu_object.Title = menu_title;
                Console.WriteLine(menu_object);

                DineOutContext.Update(menu_object);
                DineOutContext.SaveChanges();

                TempData["message"] = $"Title updated!";
                return RedirectToAction("Menu");
            }
            return RedirectToAction("OwnerLogin");
        }
        [ValidateAntiForgeryToken]
        public IActionResult Add_Update_Item(ItemViewModel itemViewModel)
        {
            if (itemViewModel.ItemId == 0)
            {
                var profile_id = HttpContext.Session.GetString("restaurant_owner_Id");
                int restaurant_id = DineOutContext.Restaurant.ToList().Find(r => r.RestaurantProfileId == Int32.Parse(profile_id)).RestaurantId;
                var menud_id = DineOutContext.Menu.Where(r => r.RestaurantId == restaurant_id ).FirstOrDefault().MenuId;


                itemViewModel.ImagePath = uploadImage(itemViewModel.Image);
                Console.WriteLine(itemViewModel);
                Item item = new Item() { MenuId = menud_id, ItemName = itemViewModel.ItemName, Description = itemViewModel.Description, Ingredients = itemViewModel.Ingredients, Price = itemViewModel.Price, Image = itemViewModel.ImagePath, Availability = itemViewModel.Availability, CreatedOn = itemViewModel.CreatedOn };
                DineOutContext.Add(item);
                DineOutContext.SaveChanges();
            }
            else
            {
                Item item = new Item()
                {
                    ItemId = itemViewModel.ItemId,
                    MenuId = itemViewModel.MenuId,
                    ItemName = itemViewModel.ItemName,
                    Description = itemViewModel.Description,
                    Ingredients = itemViewModel.Ingredients,
                    Price = itemViewModel.Price,
                    Availability = itemViewModel.Availability,
                    CreatedOn = itemViewModel.CreatedOn
             
                };
                if (itemViewModel.Image != null)
                {
                    itemViewModel.ImagePath = uploadImage(itemViewModel.Image);
                    item.Image = itemViewModel.ImagePath;
                    DineOutContext.Update(item);

DineOut/Views/Restaurant/CompletedOrders.cshtml
@model IEnumerable<Order>

@{
    ViewBag.Title = "Completed Orders";
    Layout = "_RestaurantLayout";
}

<nav class="navbar navbar-dark default-color">
    <form class="form-inline" asp-action="SearchString">
        <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Order #" name="searchedString" aria-label="Search">
            <button class="btn btn-success my-2 my-sm-0 ml-3" type="submit">Search</button>
        </div>
    </form>
</nav>
<table class="table table-sm table-striped text-center" style=" background-color: rgba(255, 226, 112, 0.8);">
	<thead>
		@if (Model.Count() == 0)
		{
			<tr>
				<th class="text-sm-center font-weight-bold">You have not completed any order(s) yet!</th>
			</tr>
		}
		else
		{
			<tr>
				<th>ID</th>
				<th>Table #</th>
				<th>Costumer ID</th>
				<th>Date</th>
			</tr>
		}
	</thead>
	<tbody>
		@foreach (var order in Model)
		{
			<tr>
				<td>
					<a asp-action="OrderDetails" asp-route-orderId="@order.OrderId">
						@order.OrderId
					</a>
				</td>
				<td>@order.TableNum</td>
				<td>
					@order.CustomerId
				</td>
				<td>@order.CreatedOn</td>
			</tr>
		}
	</tbody>
</table>

DineOut/Views/Restaurant/CurrentOrders.cshtml
@model IEnumerable<Order>

@{
	ViewBag.Title = "Order List";
	Layout = "_RestaurantLayout";
	string[] orderStatus = { "", "Accepted", "Ongoing", "Ready", "Received", "Completed" };
}

<nav class="navbar navbar-dark default-color">
    <form class="form-inline" asp-action="SearchString">
        <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Order #" name="searchedString" aria-label="Search">
            <button class="btn btn-success my-2 my-sm-0 ml-3" type="submit">Search</button>
        </div>
    </form>
</nav>
@if (Context.Request.Query["message"].Count > 0 && Context.Request.Query["message"].ToString().Length > 0)
{
	<div class="alert alert-primary" role="alert">
		Message: @Context.Request.Query["message"]
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
}
<table class="table table-sm table-striped text-center" style=" background-color: rgba(255, 226, 112, 0.8);">
	@if (Model.Count() == 0)
	{
		<thead>
			<tr>
				<th class=" text-sm-center font-weight-bold">You have no current orders yet!</th>
			</tr>
		</thead>
	}
	else
	{
		<thead>
			<tr>
				<th>Order#</th>
				<th>Table #</th>
				<th>Costumer</th>
				<th>Date</th>
				<th colspan="2">Status</th>
			</tr>
		</thead>
	}

	<tbody>
		@foreach (var order in Model)
		{
			<tr>
				<td>
					<a asp-action="OrderDetails" asp-route-orderId="@order.OrderId">
						@order.OrderId
					</a>
				</td>
				<td>@order.TableNum</td>
				<td>@order.CustomerId</td>
				<td>@order.CreatedOn</td>
				<td>
					<form asp-action="ChangeStatus" method="post">
						<input asp-for="@order.OrderId" hidden />
						<input asp-for="@order.StatusId" value="@(order.StatusId + 1)" hidden />
						<button class="btn btn-danger" type="submit">@orderStatus[order.StatusId]</button>
					</form>
				</td>
				<td>
					<form asp-action="ChangeStatus" method="post">
						<input asp-for="@order.OrderId" hidden />
						<input asp-for="@order.StatusId" value="5" hidden />
						<button class="btn btn-success" type="submit">Complete</button>
					</form>
				</td>
			</tr>
		}
	</tbody>
</table>

DineOut/Views/Restaurant/Edit.cshtml
@model Item

@{
    ViewBag.Title = "Edit";
    Layout = "_RestaurantLayout";
}

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<div class="d-flex justify-content-center">
    <form asp-action="Add_Update_Item" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="ItemId" />

        <div style="margin:10px">
            <div><input class="form-control" type="hidden" asp-for="MenuId" /></div>
        </div>
        <div style="margin:10px">
            <label class="font-weight-bold" asp-for="ItemName"></label>
            <div><input class="form-control" asp-for="ItemName" required /></div>
        </div>
        <div style="margin:10px">
            <label class="font-weight-bold" asp-for="Description"></label>
            <div><textarea class="form-control" asp-for="Description" required></textarea></div>
        </div>
        <div style="margin:10px">
            <label class="font-weight-bold" asp-for="Ingredients"></label>
            <div><textarea class="form-control" asp-for="Ingredients" required></textarea></div>
        </div>
        <div style="margin:10px">
            <label class="font-weight-bold" asp-for="Price"></label>
            <div><input type="text" id="price" asp-for="Price" required /></div>
        </div>
        <div style="margin:10px">
            <label class="font-weight-bold" asp-for="Image"></label>
            <div><input type="file" asp-for="Image" required /></div>
        </div>
        <div style="margin:10px">
            <div>
                <input class="text-lg-right" asp-for="Availability" />
                <label class="font-weight-bold" style="font-size:medium; color:dodgerblue">Available</label>
            </div>
        </div>
        <div style="margin:10px">
            <button class="btn btn-success" type="submit">Save</button>
            <a class="btn btn-light" asp-action="Menu">Cancel</a>
        </div>
    </form>
</div>


<script>
    $('#price').on('keypress', function (event) {
        var regex = new RegExp("^[.0-9]+$");
        var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
        if (!regex.test(key)) {
            event.preventDefault();
            return false;
        }
    });
</script>

DineOut/Views/Restaurant/ForgotPassword.cshtml
@model DineOut.Models.RestaurantProfile
@{
	ViewBag.Title = "Owner Change Password";
	Layout = "_IdentityLayout";
}

<form asp-action="ForgotPassword" asp-controller="Restaurant" method="post"
	  role="form">

	<div class="form-row">
		<div class="form-group col-md-12">
			<h5><label for="Email">Email</label></h5>
			<input class="form-control" type="email" asp-for="@Model.Email" placeholder="Enter Email" />
		</div>

		<div class="form-group col-md-12">
			<h5><label for="Password">New Password</label></h5>
			<input class="form-control" type="password" name="firstPassword" placeholder="Enter your new password" />
		</div>
		<div class="form-group col-md-12">
			<h5><label for="Password">Repeat Password</label></h5>
			<input class="form-control" type="password" asp-for="@Model.PasswordHash" placeholder="Confirm your new password" />
		</div>
		<div class="d-block justify-content-between">
			<button type="submit" class="btn btn-lg btn-success">Change password</button>
		</div>
	</div>

</form>

DineOut/Views/Restaurant/Menu.cshtml
@model IEnumerable<Item>
@{
    ViewBag.Title = "Your Restaurant";
    Layout = "_RestaurantLayout";
}

@if (TempData["delete"] != null)
{
    <div class="alert alert-danger mt-1">@TempData["delete"]</div>
}

<div class="d-flex justify-content-center" style="margin-top:20px">
    <table class="table table-sm table-striped text-center" style=" background-color: rgba(255, 226, 112, 0.8);">
        @if (Model.Count() == 0)
        {
            <thead>
                <tr>
                    <td class="text-center font-weight-bold">You have not created your first dish yet!</td>
                </tr>
                <tr>
                    <td class="text-center font-weight-bold">What are you waiting for?!</td>
                </tr>
            </thead>
        }
        else
        {
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Image</th>
                    <th>Dish</th>
                    <th>Price</th>
                    <th>Available</th>
                    <th>Actions</th>
                </tr>
            </thead>
        }
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ItemId</td>
                    <td><Img width="100" height="100" src="@item.Image" /></td>
                    <td>@item.ItemName</td>
                    <td>@item.Price.ToString("c")</td>
                    <td>
                        @if (item.Availability)
                        {
                            @: Yes
                        }
                        else
                        {
                            @: No
                        }
                    </td>
                    <td>
                        <form asp-action="Delete_Item" method="post">
                            <input type="hidden" name="itemID" value="@item.ItemId" />
                            <a class="btn btn-sm btn-info" asp-action="Update_Item" asp-route-itemId="@item.ItemId" asp-route-menuId="@item.MenuId">
                                Edit
                            </a>
                            <button type="button" title="Delete Item" class="btn btn-sm btn-danger" onclick="location.href='@Url.Action("Delete_Item", new { menu_id = item.MenuId, item_id = item.ItemId})'">
                                Delete
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


<div class="text-center">
    <a asp-action="Update_Item" class="btn btn-success">Add New Dish</a>
</div>

DineOut/Views/Restaurant/Notification.cshtml
@model IEnumerable<Notification> 
@{
    ViewData["Title"] = "Notification";
    Layout = "_RestaurantLayout";
}
<script>
    function changeTemplate(select) {
        const lastSelectedIndex = select['lastSelectedIndex'] || 0;
        const template = document.getElementById('template');
        const textarea = document.getElementById('content');
        if (textarea.innerHTML.trim().length > 0) {
            if (!confirm('content is not empty, do you sure to discard it.')) {
                select.selectedIndex = lastSelectedIndex;
                return;
            }
        }
        select['lastSelectedIndex'] = select.selectedIndex;
        switch (template.value) {
            case "covid":
                textarea.innerHTML = `
       Dear Custom,
 
         We send this email to all of our customers, who was dining at the restaurant before [date&time].We noticed 
         that one of customer dining at our restaurant tested positive for COVID-19. We disinfected the restaurant 
         immediately after we got the notice from Toronto Pubic Health. Receiving this email does not mean that you
         have been directly exposed to COVID-19. If you feel any discomfort, please call Toronto Public Health at
         1877-543-8931 to get more information. If your symptoms are severe, please contact the nearest hospital 
         emergence department.

         Thank you

                `;
                break;
            case "common":
                textarea.innerHTML = `
       Dear Custom,

        Our restaurant has launched new menu. All our new dishes are 50% off, the offer lasts until the 
        end of the month.Please come to visit us.
       
         Thank you

                `;
                break;
            default:
                textarea.innerHTML = '';
                break;
        }
    }
</script>
<style>
    td {
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
    }
</style>



<div style="		background-color: rgba(255, 226, 112, 0.8);">
	<h2>Notification</h2>
	<form method="post" role="form">
		<div class="form-row">
			<h5><label style="margin-right:1rem;"><b>Choose Template:</b> </label></h5>
           
			<select class="nav-item dropdown" id="template" name="template" onchange="changeTemplate(this)" required>
				<option  class="dropdown-item" value="" selected>Choose...</option>
				<option  class="dropdown-item" value="covid">Covid-19</option>
				<option  class="dropdown-item" value="common">New Menu </option>
			</select>
		</div>
		<div class="form-row" style="margin-top:2rem; margin-bottom:2rem;">
			<textarea placeholder="Email goes here..." class="form-control" id="content" name="content" rows="10"></textarea>
		</div>
		<div>
			<button class="btn btn-primary">Send Email</button>
		</div>
	</form>
</div>

DineOut/Views/Restaurant/OwnerLogin.cshtml
@model DineOut.Models.RestaurantProfile

@{
    ViewBag.Title = "Restaurant Owner Login";
    Layout = "_IdentityLayout";
}

<form asp-action="RestaurantLogin" asp-controller="Restaurant" method="post"
	  role="form">

	<div class="form-row">
		<div class="form-group col-md-6">
			<h5><label for="Email">Email</label></h5>
			<input class="form-control" type="email" asp-for="@Model.Email" id="Email" placeholder="Email" />
		</div>

		<div class="form-group col-md-6">
			<h5><label for="Password">Password</label></h5>
			<input class="form-control" type="password" asp-for="@Model.PasswordHash" id="Password" placeholder="password" />
		</div>
		<div class="d-block justify-content-between">
			<button type="submit" class="btn btn-lg btn-success">Login</button>
			<a asp-action="ForgotPassword">Forgot Password?</a>
		</div>
	</div>
	
</form>
<br />

<div class="card-footer text-center">
    <a class="card-link active font-weight-bold" asp-action="OwnerRegistration">Create New Account</a>
</div>

DineOut/Views/Restaurant/OwnerRegistration.cshtml
@model DineOut.ViewModels.ProfileViewModel
@{
	ViewBag.Title = "Restaurant Registration";
	Layout = "_IdentityLayout";
}

<form asp-action="Register" asp-controller="Restaurant" method="post"
	  role="form">

	<div class="form-row">
		<div class="form-group col-md-12">
			<h5><label for="Email">Email</label></h5>
			<input class="form-control" type="email" asp-for="@Model.restaurantProfile.Email" />
		</div>

		<div class="form-group col-md-12">
			<h5><label for="LastName"> Name</label></h5>
			<input class="form-control" type="text" asp-for="@Model.restaurantProfile.Name" />
		</div>
		<div class="form-group col-md-12">
			<h5><label for="Password">Password</label></h5>
			<input class="form-control" type="password" name="firstPassword" placeholder="Enter unique password" />
		</div>
		<div class="form-group col-md-12">
			<h5><label for="Password">Re-enter Password</label></h5>
			<input class="form-control" type="password" asp-for="@Model.restaurantProfile.PasswordHash" id="Password" placeholder="Re-enter password" />
		</div>
		<div class="form-group col-md-12">
			<h5><label for="Restaurant Name">Restaurant Name</label></h5>
			<input class="form-control" type="text" asp-for="@Model.restaurant.RestaurantName" />
		</div>

	</div>
	<div class="d-flex justify-content-between">
		<button type="submit" class="btn btn-sm btn-success">Create DineOut Account</button>
		<button type="reset" class="btn btn-sm btn-secondary">Clear Form</button>
	</div>
</form>
<br />





@*<form asp-action="Register" asp-controller="Restaurant" method="post"
	  class="form-row" role="form">
	<table class="table">
		<tr>
			<td><label for="Email">Email</label></td>
			<td><input type="email" asp-for="@Model.restaurantProfile.Email" /></td>
		</tr>
		<tr>
			<td><label for="LastName"> Name</label></td>
			<td><input type="text" asp-for="@Model.restaurantProfile.Name" /></td>
		</tr>
		<tr>
			<td><label for="Password">Password</label></td>
			<td><input type="password" name="firstPassword" placeholder="Enter unique password" /></td>
		</tr>
		<tr>
			<td><label for="Password">Re-enter Password</label></td>
			<td><input type="password" asp-for="@Model.restaurantProfile.PasswordHash" id="Password" placeholder="Re-enter password" /></td>
		</tr>
		<tr>
			<td><label for="Restaurant Name">Restaurant Name</label></td>
			<td><input type="text" asp-for="@Model.restaurant.RestaurantName" /></td>
		</tr>
		<tr>
			<td><br /></td>
			<td><br /></td>
		</tr>
	</table>

	<div>
		<button type="submit" class="btn btn-sm btn-success">Create your new DineOut Account</button>
		<button type="reset" class="btn btn-sm btn-secondary">Clear Form</button>
	</div>
</form>*@